frameworkVersion: ">=2.10.0 <3.0.0"
service: event-stream-api
provider:
  name: aws
  runtime: python3.7
  memorySize: 128
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  rolePermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/oslokommune/oslokommune-boundary"
  iamManagedPolicies:
    - !Sub "arn:aws:iam::${AWS::AccountId}:policy/event-stream-api-policy"
    - "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
    OKDATA_ENVIRONMENT: ${self:provider.stage}
    ES_API_ENDPOINT: ${ssm:/dataplatform/shared/eventdata-elasticsearch-endpoint}
    ROOT_PATH: "/streams"
    KEYCLOAK_SERVER: ${ssm:/dataplatform/shared/keycloak-server-url}
    KEYCLOAK_REALM: api-catalog
    RESOURCE_SERVER_CLIENT_ID: okdata-resource-server
package:
  exclude:
    - "**/*"
  include:
    - "clients/*.py"
    - "database/*.py"
    - "notifications/*.py"
    - "resources/*.py"
    - "services/*.py"
    - "services/template/*.py"
    - "*.py"

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
    timeout: 29
  update_cf_status:
    handler: notifications.sns_handler.handle
    events:
      - sns: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:event-stream-api-cloudformation-events"

plugins:
  - serverless-python-requirements
  - serverless-plugin-git-variables
  - serverless-es-logs

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    usePoetry: false
  esLogs:
    endpoint: ${ssm:/dataplatform/shared/logs-elasticsearch-endpoint}
    index: dataplatform-services
    filterPattern: '{ $.function_name = "*" }'
  exportGitVariables: false
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
